//View Date
export const CHANGE_DATE = "CHANGE_DATE";

//Screen Size
export const CHANGE_SIZE = "CHANGE_SIZE";

//Auth
export const ADMIN_LOGIN_LOADING = "ADMIN_LOGIN_LOADING";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";
export const GUEST_LOGIN_LOADING = "GUEST_LOGIN_LOADING";
export const GUEST_LOGIN_SUCCESS = "GUEST_LOGIN_SUCCESS";
export const GUEST_LOGIN_ERROR = "GUEST_LOGIN_ERROR";
export const ADMIN_REMOVE_ERROR = "REMOVE_ERROR";

//Logs
export const LOGS_LOADING = "LOGS_LOADING";
export const GET_LOGS_SUCCESS = "GET_LOGS_SUCCESS";
export const CREATE_LOG_SUCCESS = "CREATE_LOG_SUCCESS";
export const UPDATE_LOG_SUCCESS = "UPDATE_LOG_SUCCESS";
export const DELETE_LOG_SUCCESS = "DELETE_LOG_SUCCESS";
export const LOGS_ERROR = "LOGS_ERROR";

//Settings
export const SETTINGS_LOADING = "SETTINGS_LOADING";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const SETTINGS_ERROR = "SETTINGS_ERROR";
